74 nettoyage du code
data-players/PETR_MSB_tiers-lieux pull request #77
Opened 2022-01-25 16:02 UTC by VincentFarcy

Suite de la branche 70 : gestion_des_evenements

2022-01-25 18:22 UTC, simonLouvet requested changes

2022-01-25 18:22 UTC, simonLouvet commented on docker-compose-dev.yaml
> +      - REACT_APP_MAPBOX_ACCESS_TOKEN=pk.eyJ1Ijoic3Jvc3NldDgxIiwiYSI6ImNrbDd0b2VkMzA1dDMycG9iemU4NnpuemsifQ.HvpZ3tnweVHEUYLb0tDvTg
pas de clef en repo publique

2022-01-25 18:22 UTC, simonLouvet commented on frontend/package.json
> +    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.16.7",
pourquoi babel?

2022-01-25 18:22 UTC, simonLouvet commented on frontend/public/index.html
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.7.2/main.min.css" />
besoin d'un calendar? je prefererai une intégration avec un composant react plutôt que un import html

2022-01-25 18:22 UTC, simonLouvet commented on frontend/src/resources/Concept/AccessModality/index.js
> -    slugField: 'pair:label'
tu es sur que il n'y a plus besoin de slug?

2022-01-25 18:33 UTC, VincentFarcy commented on docker-compose-dev.yaml
> +      - REACT_APP_MAPBOX_ACCESS_TOKEN=pk.eyJ1Ijoic3Jvc3NldDgxIiwiYSI6ImNrbDd0b2VkMzA1dDMycG9iemU4NnpuemsifQ.HvpZ3tnweVHEUYLb0tDvTg
Oups, c'est corrigé

2022-01-25 18:38 UTC, VincentFarcy commented on frontend/package.json
> +    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.16.7",
C'était une option de correction proposée pour régler le problème avec les dépendances de leaflet suite à la publication semapps alpha 0.4.0-alpha.7 (0.4.0-alpha.7).
Mais finalement la modification de la propriété browserslist a suffit (voir chat https://chat.lescommuns.org/channel/semapps_dev)

2022-01-25 18:59 UTC, VincentFarcy commented on frontend/public/index.html
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.7.2/main.min.css" />
J'ai suivi passerelle normandie : https://github.com/data-players/passerelle_normandie/blob/main/client/public/index.html
Tu avais mentionné ce fichier dans l'issue : https://github.com/data-players/PETR_MSB_tiers-lieux/issues/70#issuecomment-970213497

2022-01-25 19:16 UTC, VincentFarcy commented on frontend/src/resources/Concept/AccessModality/index.js
> -    slugField: 'pair:label'
Oui la structure a changé : 
```
  dataModel: {
    types: [
      'petr:AccessModality',
    ],
    fieldsMapping: {
      title: 'pair:label'
    }
  },
```
https://github.com/data-players/PETR_MSB_tiers-lieux/blob/69_ecran_de_recherche_SPARQL/frontend/src/resources/Concept/AccessModality/index.js

2022-01-26 12:14 UTC, simonLouvet commented on frontend/src/resources/Concept/AccessModality/index.js
> -    slugField: 'pair:label'
et donc le "title" est transformé en slug pour l'appel ldp? c'est assez perturbant et pas explicite. Est ce que tu peux juste investiguer pour comprendre la mécanique et peut être créer un issue pour documenter et/ou revoir la specification pour arriver à
```fieldsMapping: { slug: 'pair:label' }```
ou
```fieldsMapping: { slug: 'pair:label',title: 'pair:label'  }```

2022-01-26 12:14 UTC, simonLouvet commented on frontend/public/index.html
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.7.2/main.min.css" />
ok, c'est l'intégration du calendar qui est mal faite et il faut avancer.

2022-01-26 13:35 UTC, VincentFarcy commented on frontend/package.json
> +    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.16.7",
oui c'est fait : https://github.com/data-players/PETR_MSB_tiers-lieux/commit/a80adae856ebae05ce96a6c25245736dee80d954

2022-01-26 13:38 UTC, VincentFarcy commented on frontend/src/resources/Concept/AccessModality/index.js
> -    slugField: 'pair:label'
Je confirme : https://github.com/assemblee-virtuelle/semapps/blob/4e8f2a9eb3528551b40539bef65629fde274136b/src/frontend/packages/semantic-data-provider/src/dataProvider/methods/create.js#L14
Je vais en parler à Seb pour la doc.

2022-01-26 13:45 UTC, VincentFarcy commented on frontend/public/index.html
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.7.2/main.min.css" />
Donc à surveiller pour la prochaine intégration

2022-01-26 14:28 UTC, simonLouvet commented on frontend/src/resources/Concept/AccessModality/index.js
> -    slugField: 'pair:label'
merci

2022-01-26 14:30 UTC, merged